FROM node:20-alpine

WORKDIR /app

# Copier les fichiers de dépendances
COPY frontend/package*.json .

# Installer les dépendances
RUN npm install

# Copier le code source
COPY frontend/src ./src
COPY shared ./src/shared

# Commande de développement avec Vite
CMD ["npm", "run", "dev"]
