services:

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.prod
    ports:
      - "8443:443"
    depends_on:
      - backend
    networks:
      - transcendence

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend/data:/app/data
    env_file:
      - ./backend/.env
    networks:
      - transcendence
    restart: unless-stopped

networks:
  transcendence:
    driver: bridge