services:

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "8443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    networks:
      - transcendence

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/data:/app/data
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    networks:
      - transcendence
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_IS_DEV=true
    networks:
      - transcendence
    restart: unless-stopped

networks:
  transcendence:
    driver: bridge