services:

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    networks:
      - transcendence

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/data:/app/data
    networks:
      - transcendence
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - transcendence
    restart: unless-stopped

networks:
  transcendence:
    driver: bridge