services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - transcendence

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
      - sqlite_data:/app/data
    networks:
      - transcendence
    restart: unless-stopped

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - transcendence
    restart: unless-stopped

volumes:
  sqlite_data:

networks:
  transcendence:
    driver: bridge