services:

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8443:443"
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./backend/uploads:/usr/share/nginx/html/uploads
    networks:
      - transcendence

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend/data:/app/data
    env_file:
      - ./backend/.env
    networks:
      - transcendence
    restart: unless-stopped

networks:
  transcendence:
    driver: bridge