services:

  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "8443:443"
      - "8080:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./backend/uploads:/usr/share/nginx/html/uploads
    networks:
      - transcendence

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
      - ./backend/uploads:/app/uploads
      - ./backend/.env:/app/.env:ro
      - ./shared:/app/src/shared
      - /app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    networks:
      - transcendence
    restart: unless-stopped

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile.dev
    volumes:
      - ./frontend:/app
      - ./frontend/.env:/app/.env:ro
      - ./shared:/app/src/shared
      - /app/node_modules
    env_file:
      - ./frontend/.env
    networks:
      - transcendence
    restart: unless-stopped

networks:
  transcendence:
    driver: bridge