FROM node:20-alpine

WORKDIR /app

# Copier les fichiers de dépendances
COPY backend/package*.json .

# Installer les dépendances
RUN npm install

# Copier le code source
COPY backend/src ./src
COPY shared ./src

# Commande de développement avec nodemon pour le hot reload
CMD ["npm", "run", "dev"]
