FROM nginx:stable-alpine

# Installer openssl dans l'image
RUN apk add --no-cache openssl bash

# Copier le script de génération de certificat dans l'image
COPY ./generate-cert.sh /usr/local/bin/generate-cert.sh
RUN chmod +x /usr/local/bin/generate-cert.sh

# Point d'entrée personnalisé qui génère le certificat puis lance nginx
CMD ["/bin/bash", "-c", "/usr/local/bin/generate-cert.sh && nginx -g 'daemon off;'"]
